services:
  dev:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - ${DOCKER_SSH_PORT}:22
      - "50052:50052"
    volumes:
      - ../../:/work/host
      - ${HOME}:${HOME}
    hostname: ${DOCKER_HOSTNAME}-focal
    environment:
      - TZ=America/Los_Angeles
    privileged: true
    network_mode: "host"
