services:
  dev:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    volumes:
      - ../../:/work/host
      - ${HOME}:${HOME}
    hostname: ${DOCKER_HOSTNAME}-focal
    environment:
      - TZ=America/Los_Angeles
    privileged: true
